# Generated by Django 4.2.16 on 2024-11-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_link_slug', models.CharField(max_length=7, unique=True, verbose_name='Слаг короткой ссылки')),
                ('redirect_url', models.URLField(blank=True, null=True, verbose_name='Оригинальная ссылка')),
                ('short_link_url', models.URLField(blank=True, null=True, verbose_name='Короткая ссылка')),
            ],
            options={
                'verbose_name': 'короткая ссылка',
                'verbose_name_plural': 'Короткие ссылки',
            },
        ),
    ]
